<a href="https://colab.research.google.com/github/sharanv16/ALIENS-vs-Bot/blob/main/AI_Proj1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Forming the Grid

In [ ]:
import random
import numpy as np

# CREATE A SQUARE GRID

create a closed square grid

*   0 implies closed cell
*   -1 implies open cell
*   1 implies alien
*   10 implies captain
*   2 implies bot


In [ ]:
def create_grid(n):
  grid = np.full((n, n), -1)
  return grid

In [ ]:
D =20
grid =create_grid(D)
print(grid)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

creating a path in the closed grid

In [ ]:
# assign a random start point
x_start =  random.randint(0,D-1)
y_start =  random.randint(0,D-1)
print(f" start = {x_start} {y_start}")
grid[x_start,y_start] = 0

 start = 1 4


In [ ]:
print(grid)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

In [ ]:
def find_closed_cells_with_one_open_neighbor(grid):
  """Finds closed cells with exactly one open neighbor, ensuring boundary checks."""
  results = []
  rows, cols = grid.shape

  for i in range(rows):
    for j in range(cols):
      if grid[i, j] == -1:  # Check for closed cells only
        adjacent_cells = [(i - 1, j), (i, j - 1), (i + 1, j), (i, j + 1)]
        adjacent_cells = [(x, y) for x, y in adjacent_cells if 0 <= x < rows and 0 <= y < cols]
        num_zero_neighbors = sum(grid[x, y] == 0 for x, y in adjacent_cells)
        if num_zero_neighbors == 1:
          results.append((i, j))
  return results

while True:
  avl_cells = find_closed_cells_with_one_open_neighbor(grid)
  if not avl_cells:
    break
  p = random.choice(avl_cells)
  grid[p] = 0

print(grid)

[[ 0  0 -1  0 -1  0 -1  0  0 -1  0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0 -1  0  0 -1  0 -1 -1  0 -1  0 -1  0]
 [ 0 -1 -1 -1  0 -1 -1  0  0  0 -1  0  0  0  0 -1  0  0 -1  0]
 [ 0  0  0  0  0  0  0 -1  0 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [-1  0 -1  0 -1  0 -1 -1  0 -1 -1  0  0  0 -1  0  0  0 -1 -1]
 [-1 -1  0  0  0 -1  0  0  0  0  0 -1  0 -1  0  0 -1  0 -1  0]
 [-1  0  0 -1  0 -1 -1 -1  0 -1  0 -1 -1  0 -1  0 -1  0  0  0]
 [ 0  0 -1  0  0  0  0  0 -1 -1  0  0  0  0 -1 -1  0 -1  0 -1]
 [-1 -1  0  0 -1  0 -1  0 -1  0  0 -1 -1  0  0  0  0 -1  0  0]
 [ 0  0  0 -1  0 -1  0  0 -1  0 -1  0  0 -1  0 -1  0 -1  0 -1]
 [ 0 -1  0 -1  0  0  0 -1  0  0 -1  0 -1  0  0  0 -1  0  0  0]
 [-1  0  0  0 -1  0 -1  0 -1  0  0  0  0 -1  0 -1  0  0 -1  0]
 [ 0  0 -1  0 -1  0  0  0  0 -1  0 -1  0  0 -1  0 -1  0 -1  0]
 [-1  0  0 -1  0  0 -1  0 -1  0  0 -1  0 -1  0  0  0  0 -1  0]
 [ 0  0 -1  0 -1  0  0 -1  0 -1  0 -1  0 -1  0 -1 -1  0 -1  0]
 [-1  0 -1  0 -1 -1  0 -1  0  0  0 -1  0  0 -1  0 -1 -1

# PLACING THE ALIENS , CAPTAIN AND BOTS AT THE STARTING POINTS

In [ ]:
rows,cols =  grid.shape
open_cells = []
for i in range(rows):
  for j in range(cols):
    if grid[i,j] == 0:
      open_cells.append((i,j))


**placing K aliens**

In [ ]:
k = 90
alien_cells = []
while k:
  r = random.choice(open_cells)
  print(r)
  grid[r] = 1
  alien_cells.append(r)
  open_cells.remove(r)
  k -=1

(9, 9)
(9, 12)
(18, 17)
(7, 3)
(19, 8)
(12, 10)
(7, 5)
(14, 5)
(16, 2)
(3, 11)
(7, 12)
(2, 4)
(1, 15)
(19, 11)
(19, 13)
(3, 0)
(0, 14)
(12, 6)
(14, 17)
(13, 19)
(6, 18)
(7, 7)
(9, 18)
(17, 11)
(4, 13)
(19, 12)
(14, 6)
(12, 12)
(8, 14)
(7, 11)
(17, 1)
(11, 17)
(13, 4)
(10, 4)
(0, 3)
(5, 8)
(0, 5)
(9, 1)
(2, 0)
(10, 9)
(19, 10)
(9, 11)
(12, 15)
(10, 19)
(4, 11)
(7, 10)
(13, 7)
(7, 1)
(5, 10)
(3, 1)
(0, 13)
(16, 0)
(15, 8)
(15, 12)
(8, 19)
(9, 7)
(0, 12)
(5, 12)
(6, 17)
(15, 15)
(11, 2)
(13, 15)
(0, 15)
(2, 16)
(5, 4)
(10, 2)
(18, 8)
(12, 0)
(4, 5)
(13, 1)
(8, 15)
(15, 6)
(7, 18)
(0, 16)
(8, 2)
(12, 8)
(4, 1)
(18, 4)
(1, 7)
(13, 2)
(15, 10)
(11, 12)
(9, 4)
(1, 12)
(8, 13)
(5, 15)
(10, 0)
(11, 10)
(2, 19)
(17, 19)


In [ ]:
print(grid)

[[ 0  0 -1  1 -1  1 -1  0  0 -1  0  0  1  1  1  1  1  0  0  0]
 [-1  0  0  0  0  0  0  1 -1  0  0 -1  1 -1 -1  1 -1  0 -1  0]
 [ 1 -1 -1 -1  1 -1 -1  0  0  0 -1  0  0  0  0 -1  1  0 -1  1]
 [ 1  1  0  0  0  0  0 -1  0 -1  0  1 -1 -1  0  0 -1 -1  0  0]
 [-1  1 -1  0 -1  1 -1 -1  0 -1 -1  1  0  1 -1  0  0  0 -1 -1]
 [-1 -1  0  0  1 -1  0  0  1  0  1 -1  1 -1  0  1 -1  0 -1  0]
 [-1  0  0 -1  0 -1 -1 -1  0 -1  0 -1 -1  0 -1  0 -1  1  1  0]
 [ 0  1 -1  1  0  1  0  1 -1 -1  1  1  1  0 -1 -1  0 -1  1 -1]
 [-1 -1  1  0 -1  0 -1  0 -1  0  0 -1 -1  1  1  1  0 -1  0  1]
 [ 0  1  0 -1  1 -1  0  1 -1  1 -1  1  1 -1  0 -1  0 -1  1 -1]
 [ 1 -1  1 -1  1  0  0 -1  0  1 -1  0 -1  0  0  0 -1  0  0  1]
 [-1  0  1  0 -1  0 -1  0 -1  0  1  0  1 -1  0 -1  0  1 -1  0]
 [ 1  0 -1  0 -1  0  1  0  1 -1  1 -1  1  0 -1  1 -1  0 -1  0]
 [-1  1  1 -1  1  0 -1  1 -1  0  0 -1  0 -1  0  1  0  0 -1  1]
 [ 0  0 -1  0 -1  1  1 -1  0 -1  0 -1  0 -1  0 -1 -1  1 -1  0]
 [-1  0 -1  0 -1 -1  1 -1  1  0  1 -1  1  0 -1  1 -1 -1

**placing the captain**

In [ ]:
r = random.choice(open_cells)
grid[r] = 10
goal = r
#not removing the cell from open cell as the bot may be able to spawn in the cell of the captain

**placing the bot**

In [ ]:
r =  random.choice(open_cells)
grid[r] = 2
start = r

FINAL START STATE OF GRID

In [ ]:
grid

array([[ 0,  0, -1,  1, -1,  1, -1,  0,  0, -1,  0,  0,  1,  1,  1,  1,
         1,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0,  1, -1,  0,  0, -1,  1, -1, -1,  1,
        -1,  0, -1,  0],
       [ 1, -1, -1, -1,  1, -1, -1,  0,  0,  0, -1,  0,  0,  0,  0, -1,
         1,  0, -1,  1],
       [ 1,  1,  0,  0,  0,  0,  0, -1,  0, -1,  0,  1, -1, -1,  0,  0,
        -1, -1,  2,  0],
       [-1,  1, -1,  0, -1,  1, -1, -1,  0, -1, -1,  1,  0,  1, -1,  0,
         0,  0, -1, -1],
       [-1, -1,  0,  0,  1, -1,  0,  0,  1,  0,  1, -1,  1, -1,  0,  1,
        -1,  0, -1,  0],
       [-1,  0,  0, -1,  0, -1, -1, -1,  0, -1,  0, -1, -1,  0, -1,  0,
        -1,  1,  1,  0],
       [ 0,  1, -1,  1,  0,  1,  0,  1, -1, -1,  1,  1,  1,  0, -1, -1,
         0, -1,  1, -1],
       [-1, -1,  1,  0, -1,  0, -1,  0, -1,  0,  0, -1, -1,  1,  1,  1,
         0, -1,  0,  1],
       [ 0,  1,  0, -1,  1, -1,  0,  1, -1,  1, -1,  1,  1, -1,  0, -1,
         0, -1,  1, -1],
       [ 1, -1,  1, -1,  1,  0

# generate cells for possible moves

In [ ]:
def get_adjacent_cells(grid, x, y):
  adjacent_cells = []
  if 0 <= x - 1 < grid.shape[0]:
    adjacent_cells.append((x - 1, y))  # Top
  if 0 <= y - 1 < grid.shape[1]:
    adjacent_cells.append((x, y - 1))  # Left
  if 0 <= x + 1 < grid.shape[0]:
    adjacent_cells.append((x + 1, y))  # Bottom
  if 0 <= y + 1 < grid.shape[1]:
    adjacent_cells.append((x, y + 1))  # Right
  return adjacent_cells

# BOT 1

Bot 1 plans the shortest path from start point to captain and ignores the position of aliens at all times

In [ ]:
grid1 = grid
#saving a copy of the original grid

Using bfs to find the shortest path

In [ ]:
def find_shortest_path(grid, start, goal):
    rows, cols = grid.shape
    queue = [(start, [start])]
    visited = set()

    while queue:
        cell, path = queue.pop(0)
        visited.add(cell)

        if cell == goal:
            return path

        for neighbor in [(cell[0] + 1, cell[1]), (cell[0] - 1, cell[1]),
                         (cell[0], cell[1] + 1), (cell[0], cell[1] - 1)]:
            if 0 <= neighbor[0] < rows and 0 <= neighbor[1] < cols and grid[neighbor] != -1 and neighbor not in visited:
                queue.append((neighbor, path + [neighbor]))

    return None

In [ ]:
def bot1_start_rescue(grid):
  bot1_path = find_shortest_path(grid,start,goal)
  return bot1_path


In [ ]:
path = bot1_start_rescue(grid1)
path

[(3, 18),
 (3, 19),
 (2, 19),
 (1, 19),
 (0, 19),
 (0, 18),
 (0, 17),
 (0, 16),
 (0, 15),
 (0, 14),
 (0, 13),
 (0, 12),
 (0, 11),
 (0, 10),
 (1, 10),
 (1, 9),
 (2, 9),
 (2, 8),
 (2, 7),
 (1, 7),
 (1, 6),
 (1, 5),
 (1, 4),
 (2, 4),
 (3, 4),
 (3, 3),
 (4, 3),
 (5, 3),
 (5, 4),
 (6, 4),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 7),
 (8, 7),
 (9, 7),
 (9, 6),
 (10, 6),
 (10, 5),
 (11, 5),
 (12, 5),
 (13, 5),
 (14, 5),
 (14, 6),
 (15, 6),
 (16, 6),
 (16, 5),
 (16, 4),
 (16, 3),
 (16, 2),
 (17, 2)]

Moving the bot step by step until the goal is reached or bot meets alien

In [ ]:
prev_cell =[start]
flag  = 0
bot_path = [start]
while flag == 0:
  for cell in path:
    print("\n \n \n \n")
    print(grid1)
    grid1[cell] = 2
    grid1[prev_cell] = 0
    prev_cell = cell
    if cell == goal:
      flag = 1
      break
    chosen_alien = random.choice(alien_cells)
    alien_possible_moves = get_adjacent_cells(grid1,chosen_alien[0],chosen_alien[1])
    random_cell_choice = random.choice(alien_possible_moves)
    print(f"Alien moves from f{chosen_alien} to {random_cell_choice}")
    if grid1[random_cell_choice] == 2:
      flag = 2
      break
    else:
      grid1[random_cell_choice] = 1
      grid1[chosen_alien] = 0
      alien_cells.remove(chosen_alien)
      alien_cells.append(random_cell_choice)
      bot_path.append(cell)
if flag == 1:
  print("GOAL REACHED")
else:
  print("GOAL FAILED")
  print(f"Alien meet bot at {random_cell_choice}")
print(bot_path)
print(f"no of steps taken = {len(bot_path)}")




 
 
 

[[ 0  0  0  0 -1  0  0  0  0 -1  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 -1  0  0 -1  1  1  0  1  1  0 -1  0]
 [ 1  1 -1 -1  0  0 -1  0  0  0 -1  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  1  0  0  0  0 -1 -1  0 -1 -1  1  0  0 -1  0  0  0 -1  1]
 [ 0  0  1  0  0  1  0  0  0  0  0  0  0 -1  0  0  1  0  0  0]
 [ 1  0  0  1  0 -1 -1  0  0  1  0  0  1  0 -1  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  1  0  1  0  0  0  1  0]
 [-1  0  0  0  1  0 -1  0 -1  0  1  0  0  0  0  0  0 -1  0  1]
 [ 0  0  1  0  1 -1  0  0  1  0  1  1  0 -1  0  0  0 -1  0  0]
 [ 0 -1  0  1  0  0  0  0  0  0 -1  0  0  0  1  0 -1  0  1  1]
 [ 1  0  0  0  0  0 -1  0 -1  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0 -1  1  0  0  1  0  0 -1  0 -1  0  1  0  0  0  0 -1  0]
 [ 0  0  0  0  0  1  0  1 -1  0  0  0  0  0  0  0  0  0 -1  0]
 [ 0  0  1  0  0  0  0  0  0 -1  0  1  0  1  1  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  1  0  0  0  0  0  0  1 