<a href="https://colab.research.google.com/github/sharanv16/ALIENS-vs-Bot/blob/main/Copy_AI_Proj1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Forming the Grid

create a closed square grid

*   0 implies closed cell
*   -1 implies open cell
*   1 implies alien
*   10 implies captain
*   2 implies bot


In [1]:
import random
import numpy as np

# MAKING THE GRID

In [22]:
#Parameters grid size,number of aliens
class Grid:
  def __init__(self,n,no_of_aliens):
    self.no_of_aliens =no_of_aliens
    self.n = n
    self.grid = np.full((self.n,self.n),-1)
    self.rows, self.cols = self.grid.shape
    # assign a random start point
    self.x_start =  random.randint(0,self.n-1)
    self.y_start =  random.randint(0,self.n-1)
    #print(f" start = {self.x_start} {self.y_start}")
    self.grid[self.x_start,self.y_start] = 0
    #start building paths from the start point

  def find_closed_cells_with_one_open_neighbor(self):
    self.results = []
    for i in range(self.rows):
      for j in range(self.cols):
        if self.grid[i, j] == -1:  # Check for closed cells only
          self.adjacent_cells = [(i - 1, j), (i, j - 1), (i + 1, j), (i, j + 1)]
          self.adjacent_cells = [(x, y) for x, y in self.adjacent_cells if 0 <= x < self.rows and 0 <= y < self.cols]
          self.num_zero_neighbors = sum(self.grid[x, y] == 0 for x, y in self.adjacent_cells)
          if self.num_zero_neighbors == 1:
            self.results.append((i, j))
    return self.results

  def create_grid(self):
    self.avl_cells = self.find_closed_cells_with_one_open_neighbor()
    #print(self.avl_cells)
    while self.avl_cells:
      p = random.choice(self.avl_cells)
      self.grid[p] = 0
      self.avl_cells = []
      self.avl_cells = self.find_closed_cells_with_one_open_neighbor()

  def find_open_cells(self):
    self.open_cells = []
    for i in range(self.rows):
      for j in range(self.cols):
        if self.grid[i,j] == 0:
          self.open_cells.append((i,j))

  def place_aliens(self):
    k = self.no_of_aliens
    self.find_open_cells()
    self.alien_cells=[]
    while k:
      r = random.choice(self.open_cells)
      self.grid[r] = 1
      self.alien_cells.append(r)
      self.open_cells.remove(r)
      k -=1


  def place_bot(self):
    r =  random.choice(self.open_cells)
    self.grid[r] = 2
    self.start = r

  def place_captain(self):
    r = random.choice(self.open_cells)
    self.grid[r] = 10
    self.goal = r

  def place_players(self):
    self.place_aliens()
    self.place_captain()
    self.place_bot()


  def show_grid(self):
    print(self.grid)



In [23]:
g = Grid(5,3)
g.show_grid()
g.create_grid()
g.place_players()
print("\n \n")
g.show_grid()

[[-1  0 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]

 

[[ 0  0  0  1  0]
 [ 0 -1 -1  0 -1]
 [10  2  0 -1  0]
 [ 1 -1  1  0  0]
 [ 0  0 -1 -1  0]]


# Bot1class dont run yet

In [27]:
#BOT1 FINDS THE SHORTEST PATH FROM THE START POSITION TO THE CAPTAIN AND MOVES
#BOT1 DOES NOT CARE ABOU THE ALIENS POSITION
#Parameters =  grid,start cell,goal cell, alien cells
class Bot1:
  def __init__(self,grid,start,goal,alien_cells):
    self.grid = grid
    self.goal = goal
    self.start = start
    self.alien_cells = alien_cells

  def find_shortest_path(self):
    rows, cols = self.grid.shape
    self.queue = [(self.start, [self.start])]
    self.visited = set()

    while self.queue:
        self.cell, self.path = self.queue.pop(0)
        self.visited.add(cell)

        if cell == self.goal:
            return self.path

        for neighbor in [(self.cell[0] + 1, self.cell[1]), (self.cell[0] - 1, self.cell[1]),
                         (self.cell[0], self.cell[1] + 1), (self.cell[0], self.cell[1] - 1)]:
            if 0 <= neighbor[0] < rows and 0 <= neighbor[1] < cols and self.grid[neighbor] != -1 and neighbor not in self.visited:
                self.queue.append((neighbor, self.path + [neighbor]))

    return None

  def bot1_rescue_path(self):
    self.bot1_path = self.find_shortest_path()
    return self.bot1_path

  def start_rescue(self,path):
    self.path=path
    self.prev_cell =[self.start]
    flag  = 0
    self.bot_path = [self.start]
    while flag == 0:
      for cell in path:
        print("\n \n \n \n")
        print(self.grid)
        self.grid[cell] = 2
        self.grid[self.prev_cell] = 0
        self.prev_cell = cell
        if cell == goal:
          flag = 1
          break
        chosen_alien = random.choice(self.alien_cells)
        ##working pending here
    #     self.alien_possible_moves = get_adjacent_cells(grid1,chosen_alien[0],chosen_alien[1])
    #     random_cell_choice = random.choice(alien_possible_moves)
    #     print(f"Alien moves from f{chosen_alien} to {random_cell_choice}")
    #     if grid1[random_cell_choice] == 2:
    #       flag = 2
    #       break
    #     else:
    #       grid1[random_cell_choice] = 1
    #       grid1[chosen_alien] = 0
    #       alien_cells.remove(chosen_alien)
    #       alien_cells.append(random_cell_choice)
    #       bot_path.append(cell)
    # if flag == 1:
    #   print("GOAL REACHED")
    # else:
    #   print("GOAL FAILED")
    #   print(f"Alien meet bot at {random_cell_choice}")
    # print(bot_path)
    # print(f"no of steps taken = {len(bot_path)}")

In [3]:
# everything works from here till bot 1 implementation

# CREATE A SQUARE GRID

In [4]:
def create_grid(n):
  grid = np.full((n, n), -1)
  return grid

In [5]:
D =20
grid =create_grid(D)
print(grid)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

creating a path in the closed grid

In [6]:
# assign a random start point
x_start =  random.randint(0,D-1)
y_start =  random.randint(0,D-1)
print(f" start = {x_start} {y_start}")
grid[x_start,y_start] = 0

 start = 13 10


In [7]:
print(grid)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

In [8]:
def find_closed_cells_with_one_open_neighbor(grid):
  """Finds closed cells with exactly one open neighbor, ensuring boundary checks."""
  results = []
  rows, cols = grid.shape

  for i in range(rows):
    for j in range(cols):
      if grid[i, j] == -1:  # Check for closed cells only
        adjacent_cells = [(i - 1, j), (i, j - 1), (i + 1, j), (i, j + 1)]
        adjacent_cells = [(x, y) for x, y in adjacent_cells if 0 <= x < rows and 0 <= y < cols]
        num_zero_neighbors = sum(grid[x, y] == 0 for x, y in adjacent_cells)
        if num_zero_neighbors == 1:
          results.append((i, j))
  return results

while True:
  avl_cells = find_closed_cells_with_one_open_neighbor(grid)
  if not avl_cells:
    break
  p = random.choice(avl_cells)
  grid[p] = 0

print(grid)

[[ 0 -1  0 -1  0  0  0 -1  0  0  0  0 -1  0 -1 -1  0  0  0  0]
 [ 0  0  0  0 -1 -1  0 -1  0 -1  0 -1 -1  0  0  0 -1  0 -1  0]
 [ 0 -1  0 -1  0 -1  0  0  0 -1 -1  0  0 -1  0 -1  0 -1  0  0]
 [-1  0  0  0  0  0 -1 -1  0  0  0 -1  0  0  0  0  0  0  0 -1]
 [ 0 -1  0 -1  0 -1  0  0 -1  0 -1  0  0 -1  0 -1 -1 -1  0 -1]
 [ 0 -1  0  0 -1 -1 -1  0 -1  0  0  0 -1  0 -1  0  0  0 -1  0]
 [ 0  0  0 -1  0 -1  0  0  0 -1  0 -1  0  0 -1 -1  0 -1  0  0]
 [-1  0 -1  0  0 -1 -1  0 -1  0  0 -1  0 -1  0  0  0  0 -1  0]
 [ 0  0  0  0 -1  0  0  0  0 -1  0  0  0  0 -1  0 -1  0  0  0]
 [-1  0 -1 -1 -1 -1  0 -1  0 -1 -1  0 -1 -1  0  0  0 -1 -1  0]
 [ 0  0  0  0 -1  0  0  0 -1  0  0  0  0  0  0 -1 -1  0  0 -1]
 [-1  0 -1 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0  0  0  0 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0 -1  0 -1  0 -1]
 [ 0 -1 -1 -1  0 -1  0 -1  0 -1  0 -1  0 -1 -1  0 -1 -1  0  0]
 [-1  0  0  0  0  0 -1  0 -1  0  0  0  0  0  0  0  0  0  0 -1]
 [ 0 -1  0 -1  0 -1  0  0 -1 -1  0 -1 -1  0 -1  0 -1 -1

# PLACING THE ALIENS , CAPTAIN AND BOTS AT THE STARTING POINTS

In [9]:
rows,cols =  grid.shape
open_cells = []
for i in range(rows):
  for j in range(cols):
    if grid[i,j] == 0:
      open_cells.append((i,j))


**placing K aliens**

In [10]:
k = 90
alien_cells = []
while k:
  r = random.choice(open_cells)
  print(r)
  grid[r] = 1
  alien_cells.append(r)
  open_cells.remove(r)
  k -=1

(11, 16)
(8, 19)
(6, 8)
(10, 3)
(9, 19)
(16, 5)
(14, 9)
(10, 2)
(13, 4)
(5, 15)
(19, 18)
(10, 10)
(5, 2)
(7, 10)
(1, 3)
(10, 0)
(16, 0)
(1, 15)
(12, 13)
(3, 8)
(12, 5)
(12, 2)
(17, 14)
(17, 18)
(1, 19)
(9, 15)
(7, 14)
(12, 14)
(18, 5)
(7, 12)
(2, 0)
(10, 18)
(3, 17)
(8, 7)
(18, 10)
(0, 9)
(8, 12)
(3, 12)
(14, 1)
(19, 15)
(19, 12)
(10, 7)
(10, 9)
(16, 4)
(15, 18)
(19, 19)
(3, 1)
(14, 15)
(6, 16)
(1, 2)
(4, 0)
(14, 7)
(15, 6)
(8, 2)
(9, 11)
(11, 8)
(12, 8)
(0, 8)
(4, 4)
(7, 3)
(17, 3)
(10, 14)
(16, 19)
(0, 17)
(5, 16)
(13, 12)
(0, 19)
(5, 11)
(1, 8)
(2, 19)
(7, 15)
(11, 17)
(8, 6)
(11, 12)
(18, 1)
(0, 18)
(9, 16)
(12, 9)
(16, 16)
(7, 1)
(12, 3)
(13, 6)
(0, 6)
(6, 4)
(1, 13)
(14, 10)
(10, 5)
(18, 19)
(17, 15)
(18, 6)


In [11]:
print(grid)

[[ 0 -1  0 -1  0  0  1 -1  1  1  0  0 -1  0 -1 -1  0  1  1  1]
 [ 0  0  1  1 -1 -1  0 -1  1 -1  0 -1 -1  1  0  1 -1  0 -1  1]
 [ 1 -1  0 -1  0 -1  0  0  0 -1 -1  0  0 -1  0 -1  0 -1  0  1]
 [-1  1  0  0  0  0 -1 -1  1  0  0 -1  1  0  0  0  0  1  0 -1]
 [ 1 -1  0 -1  1 -1  0  0 -1  0 -1  0  0 -1  0 -1 -1 -1  0 -1]
 [ 0 -1  1  0 -1 -1 -1  0 -1  0  0  1 -1  0 -1  1  1  0 -1  0]
 [ 0  0  0 -1  1 -1  0  0  1 -1  0 -1  0  0 -1 -1  1 -1  0  0]
 [-1  1 -1  1  0 -1 -1  0 -1  0  1 -1  1 -1  1  1  0  0 -1  0]
 [ 0  0  1  0 -1  0  1  1  0 -1  0  0  1  0 -1  0 -1  0  0  1]
 [-1  0 -1 -1 -1 -1  0 -1  0 -1 -1  1 -1 -1  0  1  1 -1 -1  1]
 [ 1  0  1  1 -1  1  0  1 -1  1  1  0  0  0  1 -1 -1  0  1 -1]
 [-1  0 -1 -1  0 -1  0 -1  1 -1  0 -1  1 -1  0  0  1  1 -1 -1]
 [ 0  0  1  1  0  1  0  0  1  1  0  0 -1  1  1 -1  0 -1  0 -1]
 [ 0 -1 -1 -1  1 -1  1 -1  0 -1  0 -1  1 -1 -1  0 -1 -1  0  0]
 [-1  1  0  0  0  0 -1  1 -1  1  1  0  0  0  0  1  0  0  0 -1]
 [ 0 -1  0 -1  0 -1  1  0 -1 -1  0 -1 -1  0 -1  0 -1 -1

**placing the captain**

In [12]:
r = random.choice(open_cells)
grid[r] = 10
goal = r
#not removing the cell from open cell as the bot may be able to spawn in the cell of the captain

**placing the bot**

In [13]:
r =  random.choice(open_cells)
grid[r] = 2
start = r

FINAL START STATE OF GRID

In [14]:
grid

array([[ 0, -1,  0, -1,  0,  0,  1, -1,  1,  1,  0,  0, -1,  0, -1, -1,
         0,  1,  1,  1],
       [ 0,  0,  1,  1, -1, -1,  0, -1,  1, -1,  0, -1, -1,  1,  0,  1,
        -1,  0, -1,  1],
       [ 1, -1,  0, -1,  0, -1,  0,  0,  0, -1, -1,  0,  0, -1,  0, -1,
         0, -1,  0,  1],
       [-1,  1,  0,  0,  0,  0, -1, -1,  1,  0,  0, -1,  1,  0,  0,  0,
         0,  1,  0, -1],
       [ 1, -1,  0, -1,  1, -1,  0,  0, -1,  0, -1,  0,  0, -1,  0, -1,
        -1, -1,  0, -1],
       [ 0, -1,  1,  0, -1, -1, -1,  0, -1,  0,  0,  1, -1,  0, -1,  1,
         1,  0, -1,  0],
       [ 0,  0,  0, -1,  1, -1,  0,  0,  1, -1,  0, -1,  0,  0, -1, -1,
         1, -1,  0,  0],
       [-1,  1, -1,  1,  0, -1, -1,  0, -1,  0,  1, -1,  1, -1,  1,  1,
         0,  0, -1,  0],
       [ 0,  0,  1,  0, -1,  0,  1,  1,  0, -1,  0,  0,  1,  0, -1,  0,
        -1,  0,  0,  1],
       [-1,  0, -1, -1, -1, -1,  0, -1,  0, -1, -1,  1, -1, -1,  0,  1,
         1, -1, -1,  1],
       [ 1,  0,  1,  1, -1,  1

# generate cells for possible moves

In [15]:
def get_adjacent_cells(grid, x, y):
  adjacent_cells = []
  if 0 <= x - 1 < grid.shape[0]:
    adjacent_cells.append((x - 1, y))  # Top
  if 0 <= y - 1 < grid.shape[1]:
    adjacent_cells.append((x, y - 1))  # Left
  if 0 <= x + 1 < grid.shape[0]:
    adjacent_cells.append((x + 1, y))  # Bottom
  if 0 <= y + 1 < grid.shape[1]:
    adjacent_cells.append((x, y + 1))  # Right
  return adjacent_cells

# BOT 1

Bot 1 plans the shortest path from start point to captain and ignores the position of aliens at all times

In [16]:
grid1 = grid
#saving a copy of the original grid

Using bfs to find the shortest path

In [17]:
def find_shortest_path(grid, start, goal):
    rows, cols = grid.shape
    queue = [(start, [start])]
    visited = set()

    while queue:
        cell, path = queue.pop(0)
        visited.add(cell)

        if cell == goal:
            return path

        for neighbor in [(cell[0] + 1, cell[1]), (cell[0] - 1, cell[1]),
                         (cell[0], cell[1] + 1), (cell[0], cell[1] - 1)]:
            if 0 <= neighbor[0] < rows and 0 <= neighbor[1] < cols and grid[neighbor] != -1 and neighbor not in visited:
                queue.append((neighbor, path + [neighbor]))

    return None

In [18]:
def bot1_start_rescue(grid):
  bot1_path = find_shortest_path(grid,start,goal)
  return bot1_path


In [19]:
path = bot1_start_rescue(grid1)
path

[(16, 1),
 (16, 2),
 (15, 2),
 (14, 2),
 (14, 3),
 (14, 4),
 (13, 4),
 (12, 4),
 (12, 5),
 (12, 6),
 (12, 7),
 (12, 8),
 (12, 9),
 (12, 10),
 (11, 10),
 (10, 10),
 (10, 11),
 (10, 12)]

Moving the bot step by step until the goal is reached or bot meets alien

In [20]:
prev_cell =[start]
flag  = 0
bot_path = [start]
while flag == 0:
  for cell in path:
    print("\n \n \n \n")
    print(grid1)
    grid1[cell] = 2
    grid1[prev_cell] = 0
    prev_cell = cell
    if cell == goal:
      flag = 1
      break
    chosen_alien = random.choice(alien_cells)
    alien_possible_moves = get_adjacent_cells(grid1,chosen_alien[0],chosen_alien[1])
    random_cell_choice = random.choice(alien_possible_moves)
    print(f"Alien moves from f{chosen_alien} to {random_cell_choice}")
    if grid1[random_cell_choice] == 2:
      flag = 2
      break
    else:
      grid1[random_cell_choice] = 1
      grid1[chosen_alien] = 0
      alien_cells.remove(chosen_alien)
      alien_cells.append(random_cell_choice)
      bot_path.append(cell)
if flag == 1:
  print("GOAL REACHED")
else:
  print("GOAL FAILED")
  print(f"Alien meet bot at {random_cell_choice}")
print(bot_path)
print(f"no of steps taken = {len(bot_path)}")




 
 
 

[[ 0 -1  0 -1  0  0  1 -1  1  1  0  0 -1  0 -1 -1  0  1  1  1]
 [ 0  0  1  1 -1 -1  0 -1  1 -1  0 -1 -1  1  0  1 -1  0 -1  1]
 [ 1 -1  0 -1  0 -1  0  0  0 -1 -1  0  0 -1  0 -1  0 -1  0  1]
 [-1  1  0  0  0  0 -1 -1  1  0  0 -1  1  0  0  0  0  1  0 -1]
 [ 1 -1  0 -1  1 -1  0  0 -1  0 -1  0  0 -1  0 -1 -1 -1  0 -1]
 [ 0 -1  1  0 -1 -1 -1  0 -1  0  0  1 -1  0 -1  1  1  0 -1  0]
 [ 0  0  0 -1  1 -1  0  0  1 -1  0 -1  0  0 -1 -1  1 -1  0  0]
 [-1  1 -1  1  0 -1 -1  0 -1  0  1 -1  1 -1  1  1  0  0 -1  0]
 [ 0  0  1  0 -1  0  1  1  0 -1  0  0  1  0 -1  0 -1  0  0  1]
 [-1  0 -1 -1 -1 -1  0 -1  0 -1 -1  1 -1 -1  0  1  1 -1 -1  1]
 [ 1  0  1  1 -1  1  0  1 -1  1  1  0 10  0  1 -1 -1  0  1 -1]
 [-1  0 -1 -1  0 -1  0 -1  1 -1  0 -1  1 -1  0  0  1  1 -1 -1]
 [ 0  0  1  1  0  1  0  0  1  1  0  0 -1  1  1 -1  0 -1  0 -1]
 [ 0 -1 -1 -1  1 -1  1 -1  0 -1  0 -1  1 -1 -1  0 -1 -1  0  0]
 [-1  1  0  0  0  0 -1  1 -1  1  1  0  0  0  0  1  0  0  0 -1]
 [ 0 -1  0 -1  0 -1  1  0 -1 -1  0 -1 -1  0 -1 

Start = 1 2
(0, 0)
(4, 1)
(1, 4)
(3, 2)
(0, 4)
(0, 3)
(0, 2)
(4, 0)
(1, 0)
(2, 0)
(3, 1)
(1, 2)
(2, 3)
(1, 1)
(2, 2)


IndexError: list index out of range